GET http://127.0.0.1:8081/eso-services

###

GET http://127.0.0.1:8081/eso-services/blueprints

###

GET http://127.0.0.1:8081/eso-services/deployments

###

GET http://127.0.0.1:8081/eso-services/plugins

###
